export const env = {
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || "",
  SUPABASE_ANON: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "",
  SUPABASE_SERVICE: process.env.SUPABASE_SERVICE_ROLE_KEY || "",

  LEMON_WEBHOOK: process.env.LEMON_WEBHOOK_SECRET || "",

  LEMON_PRO: process.env.NEXT_PUBLIC_LEMON_CHECKOUT_PRO || "",
  LEMON_SCALE: process.env.NEXT_PUBLIC_LEMON_CHECKOUT_SCALE || "",
  LEMON_ENT: process.env.NEXT_PUBLIC_LEMON_CHECKOUT_ENTERPRISE || "",
};
